36KmCsuy5fNRNbzeHDAGKCFObNI_5szCbqbJhpJwwLVJ3WPZ2
Invoke-WebRequest -Uri https://github.com/actions/runner/releases/download/v2.329.0/actions-runner-win-arm64-2.329.0.zip -OutFile actions-runner-win-arm64-2.329.0.zip

            - name: Setup Git for Windows SDK
  # You may pin to the exact commit or the version.
  # uses: git-for-windows/setup-git-for-windows-sdk@231fc8b8e03c9bbcc7dff73932290af700156efd
  uses: git-for-windows/setup-git-for-windows-sdk@v1.11.0
  with:
    # The subset (if any) of the SDK: minimal, makepkg-git, build-installers, or full
    flavor: # optional, default is minimal
    # The architecture of the SDK: x86_64, i686 or aarch64. Note that "aarch64" only supports the "full" flavor for now.
    architecture: # optional, default is x86_64
    # Whether to start in MSYS mode (defaults to false)
    msys: # optional, default is false
    # Where to write the SDK files
    path: # optional, default is 
    # Whether to clean up SDK files. This is only needed on self-hosted runners that are reused for multiple jobs.
    cleanup: # optional, default is false
    # Whether to log files as they are extracted
    verbose: # optional, default is 250
    # Use @actions/cache to accelerate this Action
    cache: # optional, default is auto
    # Personal access token (PAT) used to call into GitHub's REST API. We recommend using a service account with the least permissions necessary. Also when generating a new PAT, select the least scopes necessary. [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)

    github-token: # optional, default is ${{ github.token }}
          
